FROM node:22-alpine

# Required for file watching in Linux/WSL2 environments
ENV CHOKIDAR_USEPOLLING=true
ENV CHOKIDAR_INTERVAL=500

RUN apk add --no-cache bash

WORKDIR /app

COPY package.json ./

RUN npm install && chmod -R 777 /app/node_modules

EXPOSE 3000

CMD ["npm", "run", "start:dev"]
