export enum BandStatusEnum {
  Active = 'Active',
  Inactive = 'Inactive',
}

export enum BandGenreEnum {
  Rock = 'Rock',
  AlternativeRock = 'Alternative Rock',
  IndieRock = 'Indie Rock',
  HardRock = 'Hard Rock',
  ProgressiveRock = 'Progressive Rock',
  PsychedelicRock = 'Psychedelic Rock',
  BluesRock = 'Blues Rock',
  PostRock = 'Post Rock',
  Grunge = 'Grunge',
  Punk = 'Punk',
  NewWave = 'New Wave',
  Metal = 'Metal',
  HeavyMetal = 'Heavy Metal',
  DoomMetal = 'Doom Metal',
  GothicMetal = 'Gothic Metal',
  ThrashMetal = 'Thrash Metal',
  DeathMetal = 'Death Metal',
  BlackMetal = 'Black Metal',
  Pop = 'Pop',
  Jazz = 'Jazz',
  Blues = 'Blues',
  Classical = 'Classical',
  Electronic = 'Electronic',
  Techno = 'Techno',
  House = 'House',
  Ambient = 'Ambient',
  HipHop = 'Hip Hop',
  RAndB = 'R And B',
  Funk = 'Funk',
  Soul = 'Soul',
  Disco = 'Disco',
  Reggae = 'Reggae',
  Ska = 'Ska',
  Country = 'Country',
  Folk = 'Folk',
  Gospel = 'Gospel',
  Latin = 'Latin',
  Samba = 'Samba',
  Forro = 'Forro',
  BossaNova = 'Bossa Nova',
  Mpb = 'MPB',
  Axe = 'Axe',
  Pagode = 'Pagode',
  Trap = 'Trap',
  Other = 'Other',
}
